<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { createEventDispatcher, onMount, getContext } from 'svelte';
	import { config, models, tags as _tags } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';
	import XMark from '$lib/components/icons/XMark.svelte';

	const i18n = getContext('i18n');

	const dispatch = createEventDispatcher();

	export let message;

	export let show = false;

	let PROMPT_REASONS = ['PROMPT-FLAWED', 'SUBJECT-CHANGED'];
	let LIKE_REASONS = [];
	let DISLIKE_REASONS = [
		'HALLUCINATION',
		'OUTDATED-INFO',
		'OVERGENERALIZATION',
		'LOGIC',
		'MATH',
		'PARTIAL-REASONING',
		'CONTRADICTION',
		'SEQUENCE-REPETITION',
		'TURN-REPETITION',
		'WORD-SALAD',
		'VA-LLENO',
		'BRIEFTY',
		'UNCLEAR-REFERENCE',
		'TONE-SHIFT',
		'LANGUAGE-SHIFT',
		'LANGUAGE-ERROR',
		'IGNORED-CONSTRAINT',
		'OVER-REFUSAL',
		'UNDER-REFUSAL',
		'PARTIAL-ANSWER',
		'CODE',
		'TRANSLATION',
		'SUMMARIZATION',
		'FORMAT',
		'OVERCONFIDENCE',
		'CONTEXT-INCONSISTENCY',
		'CONTEXT-IGNORED',
		'NO-DISCLAIMING',
		'DIALECT',
		'CULTURE',
		'IDENTITY',
		'OVERREACHER',
		'OTHER'
	];

	let PROMPT_LANGUAGES = ['ES', 'CA', 'EN', 'EU', 'GL'];

	let tags = [];

	let reasons = [];
	let promptReasons = [];
	export let selectedPromptReasons = null;
	export let selectedReasons = null;
	export let selectedLangs = null;
	let langs = [];
	let comment = '';

	let detailedRating = null;
	let selectedModel = null;

	$: if (message?.annotation?.rating === 1) {
		reasons = LIKE_REASONS;
	} else if (message?.annotation?.rating === -1) {
		reasons = DISLIKE_REASONS;
	}
	langs = PROMPT_LANGUAGES;
	promptReasons = PROMPT_REASONS;

	$: if (message) {
		init();
	}

	const init = () => {
		if (!selectedPromptReasons) {
			selectedPromptReasons = message?.annotation?.promptReasons?.split(',') ?? [];
		}

		if (!selectedReasons) {
			selectedReasons = message?.annotation?.reason?.split(',') ?? [];
		}

		if (!selectedLangs) {
			selectedLangs = message?.annotation?.lang?.split(',') ?? [];
		}

		if (!comment) {
			comment = message?.annotation?.comment ?? '';
		}

		tags = (message?.annotation?.tags ?? []).map((tag) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = message?.annotation?.details?.rating ?? null;
		}
	};

	onMount(() => {
		if (message?.arena) {
			selectedModel = $models.find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					// @jab do not show the model name
					model: 'random'
				})
			);
		}
	});

	const saveHandler = () => {
		console.log('saveHandler');
		console.log(selectedLangs.length);
		if (selectedLangs.length < 2 || (detailedRating < 0 && selectedReasons.length < 3)) {
			toast.error($i18n.t('Please select a reason'));
			return;
		}

		dispatch('save', {
			reason: selectedReasons.toString(),
			promtpReasons: selectedPromptReasons.toString(),
			lang: selectedLangs.toString(),
			comment: comment,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});

		toast.success($i18n.t('Thanks for your feedback!'));
		show = false;
	};
</script>

{#if message?.arena}
	<div class="text-xs font-medium pt-1.5 -mb-0.5">
		{$i18n.t('This response was generated by "{{model}}"', {
			//j@ab ofuscate model
			model: 'random'
		})}
	</div>
{/if}

<div
	class=" my-2.5 rounded-xl px-4 py-3 border border-gray-100/30 dark:border-gray-850/30"
	id="message-feedback-{message.id}"
>
	<div class="flex justify-between items-center">
		<div class="text-sm font-medium">{$i18n.t('How would you rate this response?')}</div>

		<!-- <div class=" text-sm">{$i18n.t('Tell us more:')}</div> -->

		<button
			on:click={() => {
				show = false;
			}}
		>
			<XMark className={'size-4'} />
		</button>
	</div>

	<div>
		<div class="text-sm mt-1.5 font-medium">Languages</div>
		<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
			{#each langs as lang}
				<button
					class="px-3 py-0.5 border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedLangs.includes(
						lang
					)
						? 'bg-gray-100 dark:bg-gray-800'
						: ''} transition rounded-xl"
					on:click={() => {
						if (selectedLangs.includes(lang)) {
							selectedLangs.splice(selectedLangs.indexOf(lang), 1);
						} else {
							selectedLangs.push(lang);
						}
						// @jab make change so it is rective
						selectedLangs = selectedLangs;
					}}
				>
					{lang}
				</button>
			{/each}
		</div>
		<div class="text-sm mt-1.5 font-medium">Prompt Reasons</div>
		<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
			{#each promptReasons as promptReason}
				<button
					class="px-3 py-0.5 border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedPromptReasons.includes(
						promptReason
					)
						? 'bg-gray-100 dark:bg-gray-800'
						: ''} transition rounded-xl"
					on:click={() => {
						if (selectedPromptReasons.includes(promptReason)) {
							selectedPromptReasons.splice(selectedPromptReasons.indexOf(promptReason), 1);
						} else {
							selectedPromptReasons.push(promptReason);
						}
						// @jab make change so it is rective
						selectedPromptReasons = selectedPromptReasons;
					}}
				>
					{promptReason}
				</button>
			{/each}
		</div>
		{#if reasons.length > 0}
			<div class="text-sm mt-1.5 font-medium">{$i18n.t('Why?')}</div>

			<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
				{#each reasons as reason}
					<button
						class="px-3 py-0.5 border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedReasons.includes(
							reason
						)
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-xl"
						on:click={() => {
							if (selectedReasons.includes(reason)) {
								selectedReasons.splice(selectedReasons.indexOf(reason), 1);
							} else {
								selectedReasons.push(reason);
							}
							// @jab make change so it is rective
							selectedReasons = selectedReasons;
						}}
					>
						{reason}
					</button>
				{/each}
			</div>
		{/if}
	</div>

	<div class="mt-2">
		<textarea
			bind:value={comment}
			class="w-full text-sm px-1 py-2 bg-transparent outline-hidden resize-none rounded-xl"
			placeholder={$i18n.t('Feel free to add specific details')}
			rows="3"
		/>
	</div>

	<div class="mt-2 gap-1.5 flex justify-between">
		<!-- @jab begin suppress tags -->
		<div class="flex items-end group"></div>
		<!-- @jab end suppress tags -->
		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			on:click={() => {
				saveHandler();
			}}
		>
			{$i18n.t('Save')}
		</button>
	</div>
</div>
